In [5]:
import pandas as pd

kingtotal = pd.read_csv('josuncsv/king_0.csv', sep=';')
kingtotal

      label year month  day                                               text
0         0   1년   10월  10일                               임금이 수창궁(壽昌宮)에 거둥하였다.
1         0   1년   10월  10일                이조 전서(吏曹典書)              유양(柳亮) ...
2         0   1년   10월  11일  임금이 탄생일이므로 여러 신하들의 조하(朝賀)를 받고 사형(死刑)과 유형(流刑) 이...
3         0   1년   10월  12일   우현보(禹玄寶)·이색(李穡)·설장수(偰長壽) 등 30인을 외방(外方)에 종편(從便...
4         0   1년   10월  12일  공부 상정 도감(貢賦詳定都監)159)                  에서 상서(上書...
...     ...  ...   ...  ...                                                ...
2247      0   7년   윤5월   7일  사노(私奴) 오마대(吾麻大)가 그 아버지를 구타하였으므로, 명하여 이를 목 베게 하였다.
2248      0   7년   윤5월   7일                                           비가 내리었다.
2249      0   7년   윤5월   9일                                           비가 내리었다.
2250      0   7년   윤5월   9일     임금이 서강(西江)에 거둥하였는데, 경상도의 조선(漕船) 20척이 도착 정박하였다.
2251      0   3년    3월  19일  사신인 내사(內史) 노타내(盧他乃) 등이 중국 서울로 돌아가니, 임금이 여러 신하를...

[2252 rows x 5 columns]

In [6]:
from kiwipiepy import Kiwi

kiwi = Kiwi()

def kiwi_preprocess(text):
    tokens = kiwi.tokenize(text)
    return ' '.join([str(token) for token in tokens])

kingtotal['text_kiwi'] = kingtotal['text'].apply(kiwi_preprocess)